/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;
import Controle.Controler;
import java.awt.Color;
import java.io.IOException;
import observer.Observable;
import observer.Observer;
/**
 *
 * @author EL MOTTAKI
 */
public class RDate extends javax.swing.JFrame implements Observer {
    Controler controler;
    int temp=0;
    // boolean pour controler le botton de debut(toggle)
    boolean tbdebut;
    public RDate() {
        tbdebut = true;
        initComponents();
        // initialisation de controler
        controler = new Controler();
        controler.addObserver(this);
        controler.BJours();
        controler.setDD(1900);
        controler.setDF(2100);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tddebut = new javax.swing.JTextField();
        tdfin = new javax.swing.JTextField();
        Debut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Lundi = new java.awt.Button();
        Mardi = new java.awt.Button();
        Mercredi = new java.awt.Button();
        Jeudi = new java.awt.Button();
        Vendredi = new java.awt.Button();
        Samedi = new java.awt.Button();
        Dimenche = new java.awt.Button();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(153, 180, 209));

        tddebut.setText("1900");
        tddebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tddebutActionPerformed(evt);
            }
        });
        tddebut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tddebutFocusLost(evt);
            }
        });

        tdfin.setText("2100");
        tdfin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdfinActionPerformed(evt);
            }
        });
        tdfin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tdfinFocusLost(evt);
            }
        });

        Debut.setText("Debut");
        Debut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebutActionPerformed(evt);
            }
        });

        jLabel1.setText("Debut :");

        jLabel2.setText("Fin :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tddebut)
                            .addComponent(tdfin, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Debut, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tddebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tdfin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Debut)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setBackground(new java.awt.Color(102, 102, 255));
        jLabel3.setFont(new java.awt.Font("Minion Pro SmBd", 0, 52)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Random Date");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Lundi.setActionCommand("Lundi");
        Lundi.setLabel("Lundi");
        Lundi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LundiActionPerformed(evt);
            }
        });

        Mardi.setLabel("Mardi");
        Mardi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MardiActionPerformed(evt);
            }
        });

        Mercredi.setLabel("Mercredi");
        Mercredi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MercrediActionPerformed(evt);
            }
        });

        Jeudi.setLabel("Jeudi");
        Jeudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JeudiActionPerformed(evt);
            }
        });

        Vendredi.setLabel("Vendredi");
        Vendredi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendrediActionPerformed(evt);
            }
        });

        Samedi.setLabel("Samedi");
        Samedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamediActionPerformed(evt);
            }
        });

        Dimenche.setLabel("Dimenc.");
        Dimenche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DimencheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lundi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mardi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mercredi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jeudi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Vendredi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Samedi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dimenche, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Dimenche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Samedi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vendredi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jeudi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mercredi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mardi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lundi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        jLabel4.setText("BY ELMOTTAKI ");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tddebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tddebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tddebutActionPerformed

    private void DebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebutActionPerformed
        if(tbdebut)
        {
            Debut.setText("Stop");
            controler.debut();
            tbdebut = false;
        }
        else
        {
            Debut.setText("Debut");
            controler.fin();  
            tbdebut = true;
        }
    }//GEN-LAST:event_DebutActionPerformed

    private void LundiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LundiActionPerformed
       controler.clickDay(2);
    }//GEN-LAST:event_LundiActionPerformed

    private void MardiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MardiActionPerformed
        controler.clickDay(3);
    }//GEN-LAST:event_MardiActionPerformed

    private void MercrediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MercrediActionPerformed
        controler.clickDay(4);
    }//GEN-LAST:event_MercrediActionPerformed

    private void JeudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JeudiActionPerformed
        controler.clickDay(5);
    }//GEN-LAST:event_JeudiActionPerformed

    private void VendrediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendrediActionPerformed
        controler.clickDay(6);
    }//GEN-LAST:event_VendrediActionPerformed

    private void SamediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamediActionPerformed
        controler.clickDay(7);
    }//GEN-LAST:event_SamediActionPerformed

    private void DimencheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DimencheActionPerformed
       controler.clickDay(1);
    }//GEN-LAST:event_DimencheActionPerformed

    private void tddebutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tddebutFocusLost
        try{
        if(Integer.parseInt(tddebut.getText())<1900 || Integer.parseInt(tddebut.getText())>2100)
       {
          tddebut.setText("");
          Debut.setEnabled(false);
       }
        else
        {
            controler.setDD(Integer.parseInt(tddebut.getText()));
           // Debut.setEnabled(true);
        }
        }
        catch(Exception e)
        {
           tddebut.setText("");
           Debut.setEnabled(false);
        }
    }//GEN-LAST:event_tddebutFocusLost

    private void tdfinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdfinActionPerformed

    }//GEN-LAST:event_tdfinActionPerformed

    private void tdfinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tdfinFocusLost
        try {
        if(Integer.parseInt(tdfin.getText())>2100 || Integer.parseInt(tdfin.getText())<1900 || (Integer.parseInt(tdfin.getText())<Integer.parseInt(tddebut.getText())))
        {
            tdfin.setText("");
            Debut.setEnabled(false);
        }
        else
        {
            controler.setDF(Integer.parseInt(tdfin.getText()));
            Debut.setEnabled(true);
        }
        }
        catch(Exception e){
            tdfin.setText("");
            Debut.setEnabled(false);
        }
        
    }//GEN-LAST:event_tdfinFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RDate().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Debut;
    private java.awt.Button Dimenche;
    private java.awt.Button Jeudi;
    private java.awt.Button Lundi;
    private java.awt.Button Mardi;
    private java.awt.Button Mercredi;
    private java.awt.Button Samedi;
    private java.awt.Button Vendredi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tddebut;
    private javax.swing.JTextField tdfin;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String str) {
        jLabel3.setText(str);
    }

    @Override
    public void BOption() {
        tddebut.setEditable(false);
        tdfin.setEditable(false);
    }

    @Override
    public void OOption() {
        tddebut.setEditable(true);
        tdfin.setEditable(true);
    }

    @Override
    public void BJours() {
      Lundi.setEnabled(false);
      Mardi.setEnabled(false);
      Mercredi.setEnabled(false);
      Jeudi.setEnabled(false);
      Vendredi.setEnabled(false);
      Samedi.setEnabled(false);
      Dimenche.setEnabled(false);
      
    }

    @Override
    public void OJours() {
      Lundi.setEnabled(true);
      Mardi.setEnabled(true);
      Mercredi.setEnabled(true);
      Jeudi.setEnabled(true);
      Vendredi.setEnabled(true);
      Samedi.setEnabled(true);
      Dimenche.setEnabled(true);
    }

    @Override
    public void refreche(Color c) {
     try{
      jPanel3.setBackground(c);
       Thread.sleep(300);
       jPanel3.setBackground(Color.WHITE);
       Thread.sleep(100);
       jPanel3.setBackground(c);
       Thread.sleep(300);
       jPanel3.setBackground(Color.WHITE);
        }
        catch(Exception e)
        {
        }
          
    }

    @Override
    public void next() {
        temp++;
        jLabel4.setText("La Durée : "+temp);
    }
 
  
}
